# Generated by Django 5.1.6 on 2025-03-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_is_featured_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='featured',
        ),
    ]
