# Generated by Django 5.1.6 on 2025-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.BigIntegerField(default=1234567890123),
        ),
    ]
