# Generated by Django 5.1.6 on 2025-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(to='main.genre'),
        ),
    ]
