# Generated by Django 5.1.6 on 2025-04-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': '4. Products'},
        ),
    ]
